language: csharp
mono: alpha
solution: MdSharp.sln

script:
  - gulp test

cache:
  directories:
  - $HOME/node_modules
  - bin
  - packages
addons:
  apt:
    packages:
      - nodejs
install:
  - npm install

# Use container based infrastructure.
sudo: false
